---
abstract: 'Identify Brazilian states by two-letter codes and vice-versa'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-BR
provides:
  Locale::BR:
    file: lib/Locale/BR.pm
    version: 0.01
requires:
  Exporter: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
